### ISSUE TITLE
PHP Warning with new endpoint format

### ISSUE THREAD

**Issue by adamf321** [moxie-leean/wp-endpoints-static#6]
Warning: Missing argument 2 for Leean\AbstractEndpoint::filter_data(), called in /Applications/MAMP/htdocs/skaled.com-backend/wp-content/plugins/skaled/vendor/moxie-leean/wp-endpoints-static/src/StaticApi.php on line 36

**Comment by mitogh** [comment]
Do we have more info on this?

**Comment by adamf321** [comment]
Yes, look at the code-  it's missing a required param. It should either be optional or we should pass that param.

**Comment by mitogh** [comment]
Right! However the issue should be open on the abstract class instead IMHO since is there where the fix should happen.

**Comment by adamf321** [comment]
Fair enough.

**Comment by mitogh** [comment]
Closing this one here and open the issue on the parent class.
